In [1]:
import pandas as pd
import numpy as np
import joblib

In [2]:
model = joblib.load(
    '../models/random_forest.pkl'
)

print("Model loaded successfully!")

Model loaded successfully!

In [3]:
sample = {
    'Distance_km': [1200],
    
    'Fuel_Price': [95],
    
    'Carrier_Rating': [4.2],
    
    'Warehouse_Time_hr': [12],

    'Transport_Mode_Rail': [0],
    'Transport_Mode_Ship': [0],
    'Transport_Mode_Truck': [1],

    'Weather_Fog': [0],
    'Weather_Rainy': [1],
    'Weather_Storm': [0],

    'Traffic_Level_Low': [0],
    'Traffic_Level_Medium': [0]
}

In [4]:
sample_df = pd.DataFrame(sample)

sample_df

,Distance_km,Fuel_Price,Carrier_Rating,Warehouse_Time_hr,Transport_Mode_Rail,Transport_Mode_Ship,Transport_Mode_Truck,Weather_Fog,Weather_Rainy,Weather_Storm,Traffic_Level_Low,Traffic_Level_Medium
0,1200,95,4.2,12,0,0,1,0,1,0,0,0

In [5]:
prediction = model.predict(sample_df)

predicted_delay = round(
    prediction[0],
    2
)

print(
    "Predicted Delay:",
    predicted_delay,
    "hours"
)

Predicted Delay: 15.76 hours

In [6]:
if predicted_delay > 20:
    
    risk = "High"
    
    recommendation = (
        "Use alternate carrier or air transport."
    )

elif predicted_delay > 10:
    
    risk = "Medium"
    
    recommendation = (
        "Monitor shipment closely."
    )

else:
    
    risk = "Low"
    
    recommendation = (
        "Shipment is on schedule."
    )

print("Risk Level:", risk)

print("Recommendation:", recommendation)

Risk Level: Medium
Recommendation: Monitor shipment closely.

In [8]:
test_shipments = pd.DataFrame({

    'Distance_km': [500, 1800, 2500],

    'Fuel_Price': [80, 100, 110],

    'Carrier_Rating': [4.5, 3.2, 2.5],

    'Warehouse_Time_hr': [5, 20, 30],

    'Transport_Mode_Rail': [0, 1, 0],

    'Transport_Mode_Ship': [0, 0, 1],

    'Transport_Mode_Truck': [1, 0, 0],

    'Weather_Fog': [0, 0, 1],

    'Weather_Rainy': [0, 1, 0],

    'Weather_Storm': [0, 0, 1],

    'Traffic_Level_Low': [1, 0, 0],

    'Traffic_Level_Medium': [0, 1, 0]
})

test_shipments

,Distance_km,Fuel_Price,Carrier_Rating,Warehouse_Time_hr,Transport_Mode_Rail,Transport_Mode_Ship,Transport_Mode_Truck,Weather_Fog,Weather_Rainy,Weather_Storm,Traffic_Level_Low,Traffic_Level_Medium
0,500,80,4.5,5,0,0,1,0,0,0,1,0
1,1800,100,3.2,20,1,0,0,0,1,0,0,1
2,2500,110,2.5,30,0,1,0,1,0,1,0,0

In [9]:
test_shipments['Predicted_Delay_hr'] = (
    model.predict(test_shipments)
)

test_shipments

,Distance_km,Fuel_Price,Carrier_Rating,Warehouse_Time_hr,Transport_Mode_Rail,Transport_Mode_Ship,Transport_Mode_Truck,Weather_Fog,Weather_Rainy,Weather_Storm,Traffic_Level_Low,Traffic_Level_Medium,Predicted_Delay_hr
0,500,80,4.5,5,0,0,1,0,0,0,1,0,-3.2771
1,1800,100,3.2,20,1,0,0,0,1,0,0,1,23.2228
2,2500,110,2.5,30,0,1,0,1,0,1,0,0,47.3091

In [10]:
test_shipments.to_csv(
    '../reports/predicted_shipments.csv',
    index=False
)

print("Prediction report saved!")

Prediction report saved!